# Generated by Django 4.0.3 on 2022-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_drug_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.IntegerField()),
                ('drug_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='disease_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_descp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='disease_symptom_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.IntegerField()),
                ('symptom_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='disease_treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.IntegerField()),
                ('treatment_plan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=200)),
                ('d_descp', models.CharField(max_length=200)),
                ('d_qualification', models.CharField(max_length=100)),
                ('d_category', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('prescription', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='drug_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_details', models.CharField(max_length=200)),
                ('company_details', models.CharField(max_length=100)),
                ('dosage_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='symptom_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('msg', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_doctor_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('query', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('r_dt', models.CharField(max_length=100)),
                ('r_tm', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='addr',
            new_name='addr1',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.AddField(
            model_name='user_details',
            name='addr2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='addr3',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
